declare const films: ({
    id: number;
    title: string;
    year: number;
    released: string;
    runtime: string;
    genre: string[];
    director: string;
    writer: string;
    actors: string[];
    plot: string;
    country: string;
    poster: string;
    imdbRating: number;
    imdbVotes: number;
    type: string;
    boxOffice: string;
    production: string;
} | {
    id: number;
    title: string;
    year: number;
    released: string;
    runtime: string;
    genre: string[];
    director: string;
    writer: string;
    actors: string[];
    plot: string;
    country: string;
    poster: string;
    imdbRating: number;
    imdbVotes: number;
    boxOffice: string;
    production: string;
    type?: undefined;
} | {
    title: string;
    year: number;
    released: string;
    runtime: string;
    genre: string[];
    director: string;
    writer: string;
    actors: string[];
    plot: string;
    country: string;
    poster: string;
    imdbRating: number;
    imdbVotes: number;
    boxOffice: string;
    production: string;
    id?: undefined;
    type?: undefined;
})[];
interface IMovie {
    title: string;
    year: number;
    released: string;
    runtime: string;
    genre: Array<string>;
    director: string;
    writer: string;
    actors: Array<string>;
    plot: string;
    country: string;
    poster: string;
    imdbRating: number;
    imdbVotes: number;
    boxOffice: string;
    production: string;
}
declare const getAllGenre: (movies: Array<IMovie>) => Array<string>;
