export const SET_THEME = 'SET_THEME';
export const SET_BURGER_STATUS = 'SET_BURGER_STATUS';
export const SET_POST_MODAL_VISIBLE_STATUS = 'SET_POST_MODAL_VISIBLE_STATUS';
export const SET_PROFILE_MODAL_VISIBLE_STATUS = 'SET_PROFILE_MODAL_VISIBLE_STATUS';


